import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <div>
        <title>DNABreakDatabase HQU</title>
        <meta name="description" content="Generated by the Genome Insititution of HQU" />
        <link rel="icon" href="/favicon.ico" />
      </div> 
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to DBKD!
        </h1>
        <h3 className={styles.introduce_color}>
          This is a database basically involving DNA Break,ttab,ssb of specices,like mouse,human.We are dedicate to build a brand new,hostic database underlied by DNA Break.
          In our websites,you can download the lastes findinds about the DNA Break sites,with the alternative files,like bed,gtf,fasta,ect.you can on your own choice download it.
          We hope this database would be significance of our bio-seachers or related-seachers to establish meaningful projects with regard to the advanced biotechnologies.
        </h3>

        <p className={styles.description}>
          Get started by search {' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="/Submit"
            className={styles.card}
          >
            <h2>Submit &rarr;</h2>
            <p>
              Submit your own insititute to the public
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  )
}
